baseURL = 'https://rowinf.github.io/space-travel/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

relativeURLs = false

[params]
    favicon = './assets/favicon-32x32.png'
[[menu.main]]
    name = "Technology"
    weight = 4
    identifier = "technology"
    url = "/technology"